### ISSUE TITLE
Plug-in isn't working

### ISSUE THREAD

**Issue by ashsundaram** [TheInformationLab/Tableau-Extension-KeepItFresh#23]
We've been using this plug-in for couple of years now and it's a great piece of code that has been working perfectly fine for so long. Today, it seems that the link is broken and hence it isn't refreshing the dashboard anymore. Has there been any changes to the plug-in lately? Could you please bring the T-REX back alive? Below is what I see when i try to access the extension URL.

![image](https://user-images.githubusercontent.com/36607212/140640201-40513be3-3e83-45e2-9b4c-fac2919abd80.png)

**Comment by ashsundaram** [comment]
You can ignore this issue, turns out there is something blocking the extension internally in our network. I did have our cyber security team check first before raising it here but turns out it's an internal issue. Once again, thank you for this plug-in, very helpful indeed.

**Comment by andre347** [comment]
Thanks for letting me know. I just checked this and indeed it's running fine.

Glad to hear you're finding this extension helpful!
